# Generated by Django 3.0.7 on 2020-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Coursecode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
