# Generated by Django 3.0.7 on 2020-09-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_auto_20200912_0210'),
        ('management', '0002_subject_coursecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.Staff'),
        ),
        migrations.AddField(
            model_name='year',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Department'),
        ),
        migrations.AddField(
            model_name='year',
            name='subjects',
            field=models.ManyToManyField(to='management.Subject'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
