# Generated by Django 3.0.7 on 2020-08-24 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('staffs', '0003_remove_staff_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='current_status',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('lecturer', 'Lecturer')], default='assistant', max_length=10),
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('head', 'Head'), ('dean', 'Dean'), ('director', 'Director')], default='head', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('fromDate', models.DateField(default=django.utils.timezone.now)),
                ('toDate', models.DateField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department')),
            ],
        ),
    ]
