# Generated by Django 3.0.7 on 2020-09-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_auto_20200824_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Subject',
        ),
    ]
