# Generated by Django 3.0.7 on 2020-08-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname', 'current_year', 'current_dept']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='Gr_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='others',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='students/pic/'),
        ),
    ]
