# Generated by Django 3.0.7 on 2020-08-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200817_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Gr_number', 'Roll_number']},
        ),
    ]
