# Generated by Django 3.0.7 on 2020-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200817_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('regular', 'Regular'), ('drop', 'Drop')], default='regular', max_length=10),
        ),
    ]
