# Generated by Django 3.0.7 on 2020-09-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_auto_20200912_0210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_users', '0005_auto_20200829_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.Staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
